### Project-specific makefile

# project_name = program
# sources =
# language = c++

# cross_compile =
# w_flags =
# c_flags =
# cflags +=
# cxxflags +=

# language =

# defines +=
# include_dirs +=
# includes +=
libs += pthread

# c_std =
# cxx_std =

.DEFAULT_GOAL := all

include Makefile.deploy
